# THIS WORKFLOW IS PRONE TO FAILURE, IT DOESN't NECESSARILY MEAN THAT THE WEBSITE WILLL FAIL LOADING
# IF YOU CAN FIX THIS WORKFLOW PLEASE DO. THE PROBLEM EXISTS AT LINE 26.

# The puprpose of this workflow is to run the ./blog_script.sh automatically. The script takes the number of blogs and updates
# it in the appropriate files (modals.html, portfolio_grid.html). This update will fix the logic so it can properly display
# projects and any HIGHLIGHTED blogs.

name: Blogpost Updates

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update Number of Blogs # Replaces the number of blog posts if there are any changes
      run: |
        ./blog_script.sh 
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Update blog post count"
        if [ $(echo $?) == 0 ]; then
          git push origin HEAD:${{ github.ref }}
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}